### PR TITLE
Adds ability to make a shadow on the badge. Totally customizable.

### PR DESCRIPTION
**Pull request by markrickert**
If the shadow offset is set to something other than CGSizeZero, it renders the shadow on the badge.

Usage example is commented out in the demo project.

### CODE REVIEW

**Comment by mamaral** [comment]
I like this in principle and it's well done, I'm just wondering if adding a layer of complexity on top of existing CALayer properties is a good thing or not. For example, if someone manually changed the layer properties, these  new properties would be out of sync.

**Comment by markrickert** [comment]
I see your point. It might be that a section in the readme about the badge being a standard CALayer and you can add properties to it like a shadow might be sufficient.

**Comment by mamaral** [comment]
Yeah, perhaps mentioning that a `UIView` subclass would suffice.

**Comment by mamaral** [comment]
Thanks for the feedback!

**Pull request closed without merging**
